# Config file for automatic testing at travis-ci.org
dist: xenial
language: python

sudo: false
python:
  - "3.8"
  - "3.7"
  - "3.6"
  - "3.5"
env:
  - DJANGO="Django>=3.0,<3.1"
  - DJANGO="Django>=2.2,<2.3"
  - DJANGO="Django>=2.1,<2.2"
  - DJANGO="Django>=2.0,<2.1"
  - DJANGO="Django>=1.11,<1.12"
  - DJANGO="https://github.com/django/django/archive/master.tar.gz"
before_install:
  - pip install -q $DJANGO
install:
  - python setup.py develop
script:
  - python setup.py test
after_success:
  - coveralls
matrix:
  exclude:
    - python: "3.5"
      env: DJANGO="Django>=3.0,<3.1"
    - python: "3.5"
      env: DJANGO="https://github.com/django/django/archive/master.tar.gz"
  allow_failures:
    - env: DJANGO="https://github.com/django/django/archive/master.tar.gz"
